# Generated by Django 5.1.7 on 2025-03-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstalledModules',
            new_name='InstalledModule',
        ),
    ]
