# Generated by Django 5.1.7 on 2025-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0002_rename_installedmodules_installedmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
            ],
        ),
    ]
