# Generated by Django 5.1.7 on 2025-03-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine_app.installedmodule'),
            preserve_default=False,
        ),
    ]
