# Generated by Django 5.1.7 on 2025-03-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0004_product_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
