# Generated by Django 5.1.7 on 2025-03-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0005_product_price_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'module'), name='unique_product_per_module'),
        ),
    ]
