# Generated by Django 5.1.7 on 2025-03-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0006_alter_product_name_product_unique_product_per_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFieldMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Integer'), (2, 'String')])),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine_app.installedmodule')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFieldInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine_app.product')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine_app.additionalfieldmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFieldStr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine_app.additionalfieldmetadata')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine_app.product')),
            ],
        ),
    ]
