# Generated by Django 5.1.7 on 2025-03-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0007_additionalfieldmetadata_additionalfieldint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
